rm -rf CMakeCache.txt
rm -rf CMakeFiles/2.8.12.2/CMakeCXXCompiler.cmake
rm -rf CMakeFiles/2.8.12.2/CMakeDetermineCompilerABI_CXX.bin
rm -rf CMakeFiles/2.8.12.2/CMakeSystem.cmake
rm -rf CMakeFiles/2.8.12.2/CompilerIdCXX/CMakeCXXCompilerId.cpp
rm -rf CMakeFiles/CMakeDirectoryInformation.cmake
rm -rf CMakeFiles/Makefile.cmake
rm -rf CMakeFiles/Makefile2
rm -rf CMakeFiles/TargetDirectories.txt
rm -rf CMakeFiles/cmake.check_cache
rm -rf CMakeFiles/progress.marks
rm -rf Makefile
rm -rf cmake_install.cmake
rm -rf src/CMakeFiles/CMakeDirectoryInformation.cmake
rm -rf src/CMakeFiles/progress.marks
rm -rf src/Makefile
rm -rf src/cmake_install.cmake
rm -rf test/CMakeFiles/CMakeDirectoryInformation.cmake
rm -rf test/CMakeFiles/progress.marks
rm -rf test/CMakeFiles/run_tests.dir/CXX.includecache
rm -rf test/CMakeFiles/run_tests.dir/DependInfo.cmake
rm -rf test/CMakeFiles/run_tests.dir/build.make
rm -rf test/CMakeFiles/run_tests.dir/cmake_clean.cmake
rm -rf test/CMakeFiles/run_tests.dir/depend.internal
rm -rf test/CMakeFiles/run_tests.dir/depend.make
rm -rf test/CMakeFiles/run_tests.dir/flags.make
rm -rf test/CMakeFiles/run_tests.dir/link.txt
rm -rf test/CMakeFiles/run_tests.dir/progress.make
rm -rf test/CTestTestfile.cmake
rm -rf test/Makefile
rm -rf test/cmake_install.cmake
